#ansible-playbook -i hosts install.yml --syntax-check
- hosts: all 
  #become: yes
  tasks:
    - name: Load based on OS 
      include_vars: "{{ item }}"  # brings variable pkg 
      with_first_found:     # load a file which is found at first 
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/os_defaults.yml"
    - name: install {{ pkg }}
      command: >
        echo 'package:
        name: "{{ pkg }}"
        state: present'
      notify:
        - Copy index.html
        - Restart service
  handlers:
    - name: Copy index.html
      command: >
        echo 'copy:
        src: index.html
        dest: /var/www/html/'
    - name: Restart service
      command: >
        echo 'service:
        name: "{{ pkg }}"
        state: restarted'