# ansible-playbook -i hosts complex_mods.yml --syntax-check
- hosts: all 
  tasks:
    # 1. Write a python script to dump PATH and USER env in remote machine
    - name: Copy script to remote 
      vars:
        env_var: ['PATH', 'USER']
        script_suffix: py
      template:
        src: dump_py_script.j2
        dest: some_script.{{ script_suffix }}
        trim_blocks: yes
        lstrip_blocks: yes
    #2. Copy header.txt to remote containing "Key value"
    #create header.txt by echo "Key value" > header.txt in Ansible controller
    #then use copy module to copy to remote 
    - name: Copy header.txt to remote 
      copy:
        src: header.txt 
        dest: header.txt 
    #3.Execute step1 script and redirect to header.txt using shell 
    - name: Execute script 
      shell: python some_script.py >> header.txt 
    #clean downloaded/ at first using file module at localhost 
    - name: Remove downloaded
      file:
        path: downloaded/
        state: absent
      delegate_to: localhost 
      run_once: yes         
    #Bring all remote's header.txt to local downloaded/ 
    - name: Bring header.txt 
      fetch:
        src: header.txt
        dest: downloaded
    
    
    
    